using AdvanceAPI.DTO.Advance;
using AdvanceAPI.DTO.Advance.Bill;
using AdvanceAPI.DTO.DB;
using System.Data;

namespace AdvanceAPI.IRepository
{
    public interface IAdvanceRepository
    {
        Task<DataTable> CheckPreviousPendingBill(string RefNo);
        Task<DataTable> GetVendorDetails(string VendorId);
        Task<DataTable> PurchaseApprovalDetails(string RefNo);
        Task<DataTable> getVendorDetails(string VendorId, string Office);
        Task<DataTable> GetBalanceDetails(string RefNo);
        Task<DataTable> GetPreviousDetails(string RefNo);
        Task<DataTable> GetDepartmentHod(string Department);
        Task<DataTable> GetAdvanceRefNo();
        Task<DataTable> GetBackValue(string Type);
        Task<DataTable> GetPurchaseApprovalPValues(string RefNo);
        Task<int> SaveAdvance(GenerateAdvancerequest req, string EmpCode, string EmpName, string RefNo, string FirmName, string FirmPerson, string FirmEmail, string FirmPanNo, string FirmAddress, string FirmContactNo, string FirmAlternateContactNo, string BackValue, string PurchaseApprovalDetails,string PrevRefNo);
        Task<DataTable> FinalAuth(string CampusCode);
        Task<DataTable> GetVendorTextValue(string VendorId);
        Task<DataTable> GetMyAdvanceDetails(string Status, string Session, string CampusCode, string RefNo,string Type,string EmpCode, string Department, string itemsFrom, string noOfItems);
        Task<int> DeleteAdvance(string RefNo, string EmpCode);
        Task<DataTable> GetPassApprovalDetails(string EmpCode, string EmpCodeAdd, string Type, GetMyAdvanceRequest req);
        Task<DataTable> GetApprovalType();
        Task<int> AdvanceApproveDetails(string EmpCode, string EmpName, PassApprovalRequest req);
        Task<DataTable> IsApproveDetails(string EmpCode, string EmpName, PassApprovalRequest req);
        Task<int> ApproveFinalStatus(string EmpCode, string EmpName, PassApprovalRequest req);
        Task<int> InsertBillBase(string EmpCode, string EmpName, PassApprovalRequest req);
        Task<DataTable> BillBaseDetails(string EmpCode, string EmpName, PassApprovalRequest req);
        Task<int> InsertBillAuthority(string BillTransId, string RefNo);
        Task<int> UpdateBillStatus(string BillTransId, string RefNo);
        Task<int> RejectAdvanceApproval(string EmpCode, string EmpName, PassApprovalRequest req);
        Task<DataTable> GetPurchaseBasicForBill(string RefNo);
        Task<DataTable> GetPurchaseBasicForBillAgainstAdvance(string RefNo);
        Task<DataTable> GetOffices(string VendorId);
        Task<string> CheckWarrentyUploadeOrNot(string RefNo);
        Task<DataTable> GetFinanceAuthority();
        Task<DataTable> Get4Auth();
        Task<DataTable> GetThirdAuth();
        Task<DataTable> LockMenu(string EmpCode);
        Task<DataTable> CanGenerateBill(string Type, string EmpCode, bool IsThousand, string RefNo = "");
        Task<DataTable> LoadApprovalDetails(string Type, string EmpCode);
        Task<DataTable> GetbasicPrintDetails(string Id);
        Task<DataTable> GetContactNo(string EmpCode);
        Task<DataTable> GetVisitBasicDetails(string Type, string EmpCode, string Prefix);
        Task<DataTable> GetPartnerVisit(string Type, string EmpCode, string Prefix);
        Task<DataTable> GetSchoolVisit(string Type, string EmpCode, string Prefix);
        Task<DataTable> LoadSubFirm(int VendorId);
        Task<DataTable> LoadOffices(string RefNo, string VendorId);
        Task<DataTable> GetDepartDetails(string Values, string Type);
        Task<DataTable> GetBillBaseRefNo();
        Task<DataTable> getPurchaseApprovalDetails(string RefNo);
        Task<int> SaveBillSave(string EmpCode, string EmpName, AddBillGenerateRequest req, string BillBaseREfNo);
        Task<int> SaveBillAuth(string EmpCode, string EmpName, AddBillGenerateRequest req, string BillBaseREfNo);
        Task<int> UpdatePdf(string RefNo);
        Task<int> UpdateExcel(string RefNo);
        Task<DataTable> GetFirm(string cond);
        Task<DataTable> GetDateLock(string Type);

        Task<DataTable> GetMissionAdmissionReturnTypes();
        Task<DataTable> GetAdvancePrintApprovalDetails(string ReferenceNo);
        Task<DataTable> GetAdvanceOfficeMappingEmployeeCodes(string OfficeName, string Session);
        Task<DataTable> GetAdvanceEmployeeLeaveDetails(string EmployeeIds, string AdvanceFrom, string AdvanceTo);
        Task<DataTable> GetAdvanceBillSummaryDetails(string ReferenceNo);
        Task<DataTable> GetAdvancePaymentDetailsByPaymentGroupId(string ReferenceNo);
        Task<DataTable> GetAdvancePaymentDetailsByReferenceNo(string ReferenceNo);
        Task<DataTable> GetAdvancePaymentTransactionIdsByReferenceNo(string ReferenceNo);
        Task<DataTable> GetAdvanceBillDetailsByTransactionIds(string TransactionIds);
        Task<DataTable> GetAdvanceBillBillDistributionDetailsById(string BillId);
        Task<DataTable> GetAdvanceBillAgainstBaseDistributionDetailsByTransactionIds(string TransactionIds);
        Task<DataTable> GetAdvanceOtherSummaryDistributionDetailsByReferenceNo(string ReferenceNo);
        Task<DataTable> GetAdvanceAmountIssuedAgainstBudgetByReferenceNo(string ReferenceNo);
        Task<DataTable> GetAdvanceBudgetUsageSessionWiseByReferenceNo(string ReferenceNo);
        Task<DataTable> GetAdvanceBudgetUsageMonthWiseByReferenceNo(string ReferenceNo);
        Task<DataTable> GetrefnoForGenerateBillAdvance(string Type, string EmpCode,string RefNo);
        Task<DataTable> Auth1AdvanceBill(string refNo);
        Task<DataTable> Auth2AdvanceBill(string refNo);
        Task<DataTable> Auth3AdvanceBill(string refNo);
        Task<DataTable> Auth4AdvanceBill(string refNo);
        Task<DataTable> GetAuthAdvanceBillAuth4(string Campus);
        Task<DataTable> GetAuthAdvanceBillAuth1(string Campus);
        Task<DataTable> GetAuthAdvanceBillAuth2(string Campus);
        Task<DataTable> GetApprovalBill(string EmpCode, string Type, GetApprovalBillRequest req);
        Task<DataTable> GetIssuedAmount(string TransId);
        Task<DataTable> GetApprovalAuthority(string Tid);
        Task<DataTable> GetIssuedAmounREadyApproval(string TransId);
        Task<int> UpdateBillBase(string Cond, string TransId, string WarId, List<SQLParameters> lst);
        Task<int> UpdateRemark(string Remark, string TransId);
        Task<DataTable> GetEditBillDetails(string RefNo);
        Task<DataTable> GetRefAuth(string refNo);
        Task<int> UpdateDeleteStatus(string BillId);
        Task<int> InsertDeleteLog(string BillId, string EmpCode);
        Task<int> DeleteBillBase(string BillId);
        Task<int> DeleteBillAuth(string BillId);
        Task<int> UpdateBill(string EmpCode, string EmpName, AddBillGenerateRequest req, string BillBaseREfNo);
        Task<DataTable> GetBillDetails(string TransId);
        Task<DataTable> GetImprestByBillTransactionId(string TransId);
        Task<DataTable> GetWorkshopBillDetails(string TransId);
        Task<DataTable> GetRelativeContactNo(string EmpCode);
        Task<DataTable> GetApprovalsAuthSummary(string TransId);
        Task<DataTable> GetBillIssues(string TransId);
        Task<DataTable> RowColor(string TransId);
        Task<DataTable> RowColorReadyAmount(string TransId);
        Task<DataTable> GetAuthStatusBill(string TransId);
        Task<DataTable> GetVenderRegisterDetails(string VendorId);
        Task<DataTable> GetTransDetails(string TransId);
        Task<DataTable> BillBaseDetails(string TransId);
        Task<DataTable> CheucqAuth(string TransId, string SeqNo);
        Task<DataTable> GEtSpecialVendor(string VendorId);
        Task<DataTable> GetPerson(string campusCode);
        Task<DataTable> GetBillauth(string campusCode);
        Task<DataTable> GetFirstSecond(string campusCode);

        Task<DataTable> GetBillApprovalFilterSessions();
        Task<DataTable> GetBillApprovalFilterInitiatedBy();
        Task<DataTable> GetBillApprovalFilterChequeBy();
        Task<DataTable> GetBillApprovalAgencyBillIds();
        Task<DataTable> GetBillApprovalDetails(GetBillApprovalRequest? getBillApprovalRequest, string employeeId, string role);
        Task<DataTable> GetBillApprovalAdvanceBudgetSummary(string referenceNo);
        Task<DataTable> GetBillApprovalAdvanceExcludeMedBudgetSummary(string referenceNo);
        Task<DataTable> GetBillApprovalAdvanceBudgetSummaryApprovalDetails(string referenceNo);
        Task<DataTable> GetBillApprovalAdvanceMedReleaseOrder(string referenceNo);
        Task<DataTable> GetBillApprovalAdvanceUserIdentity(string referenceNo);
        Task<DataTable> GetBillApprovalAdvanceImprestDetails(string referenceNo);
        Task<DataTable> GetBillApprovalAdvanceBillApprovalAuthorities(string referenceNo);
        Task<DataTable> GetBillApprovalAdvancePreviousRejections(string type, string referenceNo);
        Task<DataTable> GetBillApprovalAdvanceBillBaseExtra7Details(string referenceNo);
        Task<DataTable> GetBillApprovalAdvanceBillApprovalAuthoritiesTimeLimit(string referenceNo);
        Task<DataTable> GetBillApprovalAdvanceBillTransactionIssueECol6(string referenceNo);
        Task<DataTable> GetBillApprovalAdvanceApprovalAuthoritiesLimit(string referenceNo);
        Task<DataTable> GetBillApprovalAdvanceBillTransactionIssueChequeECol6(string referenceNo);
        Task<DataTable> GetBillApprovalAdvanceBillChequeApprovalAuthorities(string referenceNo, string sequenceId);
        Task<DataTable> GetBillApprovalAdvanceBillChequeApprovalAuthoritiesLimit(string referenceNo, string sequenceId);
        Task<DataTable> GetBillApprovalAdvanceIsBillLate(string referenceNo);
        Task<DataTable> GetBillApprovalAdvanceAllBillDetails(string referenceNo);
        Task<DataTable> GetBillApprovalAdvanceAllBillDetailsIssue(string referenceNo);
        Task<DataTable> GetBillApprovalAdvanceAllBillDetailsIssueAuthoritiesStatus(string referenceNo, string sequenceId);
        Task<DataTable> GetBillApprovalAdvanceAllBillDetailsIssueHostelDistribution(string referenceNo);
        Task<DataTable> GetBillApprovalAdvanceAllBillDetailsIssueVehicleDistribution(string referenceNo);
        Task<DataTable> GetBillApprovalAdvanceAllBillDetailsIssueVehiclePreviousBills(string referenceNo);

        Task<DataTable> GetChequeAuth();
        Task<DataTable> PaymentDetails();
        Task<DataTable> GetTransactionNo(string TransId);
        Task<int> UpdateBillBase(string EmpCode, string EmpName, string PaidAmount, string TransId);
        Task<int> InsertBillTransactionIssue(string EmpCode, string EmpName, SaveCheDetailsRequest req);
        Task<int> UploadChequeApproval(string EmpCode, string EmpName, SaveCheDetailsRequest req);
        Task<int> SaveFileCheque(string EmpCode, string EmpName, SaveCheDetailsRequest req);
        Task<DataTable> GetOtherApproval(string EmpCode, string AddEmpCode, string TransId, string SeqId);


        Task<int> UpdateApprovalAuthorityWithOutSeqNo(string EmpCode, string EmpAddCode, string EmpName, string TransId, string Designation);
        Task<DataTable> GetPendingAuthority(string TransId);
        Task<int> UpdateBillStatus(string EmpName, string Reason, string TransId);
        Task<int> UpdateBillReason(string EmpName, string Reason, string TransId);
        Task<int> ApprovalAuthWithSeqNo(string EmpCode, string EmpAddCode, string EmpName, string Designation, string TransId, string SeqNo);
        Task<DataTable> GetCequePendingAuthority(string TransId, string SeqNo);
        Task<DataTable> GetSmsDetails(string TransId);
        Task<int> UpdateScheduled(string TransId);
        Task<int> UpdateTransactionIssued(string Sms, string TransId, string SeqNo, string Remark, string EmpName);
        Task<int> UpdateBillTransactionIssuedTblAllAuthApproved(string EmpName, string Reason, string TransId, string SeqId);
        Task<DataTable> GetPendingRejectedRecord(string TransId);
        Task<int> UpdateREadyToIssueAmount(string TransId);
        Task<int> ApproveApplication(string EmpCode, string TransId);
        Task<int> UpdateRejectRecord(string EmpCode, string EmpName, string EmpAddCode, string Designation, string TransId);
        Task<int> UpdateBillBaseReject(string TransId, string Reason, string EmpName);
        Task<int> UpdateAppAuthWithSeq(string EmpCode, string EmpAddCode, string Designation, string EmpName, string TransId, string SeqNo);
        Task<int> UpdateBillTransactionIssueReject(string EmpCode, string TransId, string SeqNo, string Reason, string EmpName);
        Task<int> UpdateBillRejectStatus(string TransId);
        Task<int> BillAmountUpdate(string TransId, string SeqNo,string EmpName);
        Task<int> InsertInBackUpDeleteCheque(string EmpName, string TransId, string SeqNo);
        Task<int> DeleteChequeTransaction(string TransId, string SeqNo);
        Task<int> UpdateAmount(string EmpName, string TransId, string SeqNo);
        Task<DataTable> Purchasetime(string RefNo);
        Task<DataTable> AdvanceSummary(string RefNo,string Type);
        Task<DataTable> BillSummary(string Ids);
        Task<DataTable> ChequeDetails(string Ids);
        Task<DataTable> BillDetaild(string Ids);
        Task<DataTable> GetAuthority(string strId);
        Task<DataTable> GetCheque(string TandId);
        Task<DataTable> GetChequeAuthority(string strId);

    }
}
