namespace AdvanceAPI.SQLConstants.FirmPaidReport
{
    public class FirmReportSql
    {
        public const string GET_VENDER_ID_OFFICES= "Select VendorID,IFNULL(Col3,'----') 'Col3' from bill_base where TransactionID=@TransactionID;";
        public const string VENDOR_REG_DETAILS= "select * from purchase.vendorregister where VendorID=@VendorID;";

        public const string DEPARTMENT_WISE_DETAILS = "select '' as 'SNO',RelativePersonName 'Person',B.Remark 'Purpose',B.IssuedAmount,TransactionNo 'Tran',CAST(DATE_FORMAT(A.Col2,'%b %d, %y') as CHAR) 'Ini',CAST(IFNULL(DATE_FORMAT(B.SignedOn,'%b %d, %y'),\r\n'---') as CHAR) 'Sign',CAST(IFNULL(DATE_FORMAT(B.Col4,'%b %d, %y'),'---') as CHAR) 'Clr',CONCAT(CAST(B.TransactionID as CHAR),'#',CAST(B.SequenceID AS CHAR)) 'CONCAT',\r\nIF(A.VendorID!=B.CVId,B.CVName,'') as 'FName',IF(A.Col5!=B.CVAddName And IFNULL(B.CVAddName,'')!='' And IFNULL(B.CVAddName,'') not like '%---%',B.CVAddName,'') as 'MadName' from \r\nbill_base A, bill_transaction_issue B where A.TransactionID=B.TransactionID And B.Col3 is  NULL @Condition  order by BillExtra4 Desc";
        public const string DEPARTMENT_WISE_DETAILS_WITHOUT_ADVANCE = "select '' as 'SNO',RelativePersonName 'Person',B.Remark 'Purpose',B.IssuedAmount,TransactionNo 'Tran',CAST(DATE_FORMAT(A.Col2,'%b %d, %y') as CHAR) 'Ini',CAST(IFNULL(DATE_FORMAT(B.SignedOn,'%b %d, %y'),'---') as CHAR) 'Sign',CAST(IFNULL(DATE_FORMAT(B.Col4,'%b %d, %y'),'---') as CHAR) 'Clr',CONCAT(CAST(B.TransactionID as CHAR),'#',CAST(B.SequenceID AS CHAR)) 'CONCAT',IF(A.VendorID!=B.CVId,B.CVName,'') as 'FName',IF(A.Col5!=B.CVAddName And IFNULL(B.CVAddName,'')!='' And IFNULL(B.CVAddName,'') not like '%---%',B.CVAddName,'') as 'MadName' from bill_base A, bill_transaction_issue B where A.TransactionID=B.TransactionID And B.Col3 is  NULL @Condition And A.ForType!='Advance Bill' order by BillExtra4 Desc;";
        public const string VENDER_ADVANCE_BILL = "select '' as 'SNO',RelativePersonName 'Person',B.Remark 'Purpose',B.IssuedAmount,TransactionNo 'Tran',CAST(DATE_FORMAT(A.Col2,'%b %d, %y') as CHAR) 'Ini',CAST(IFNULL(DATE_FORMAT(B.SignedOn,'%b %d, %y'),\r\n'---') as CHAR) 'Sign',CAST(IFNULL(DATE_FORMAT(B.Col4,'%b %d, %y'),'---') as CHAR) 'Clr',A.TransactionID,B.SequenceID,DATE_FORMAT(BillUpto,'%d %b, %Y') 'BU',CONCAT(CAST(B.TransactionID as CHAR),'#',\r\nCAST(B.SequenceID AS CHAR)) 'CONCAT' from bill_base A, bill_transaction_issue B where A.TransactionID=B.TransactionID And B.Col3 is  NULL @Condition \r\n And A.ForType='Advance Bill' order by\r\n IFNULL(B.Col4,SignedOn) Desc;";
        public const string BILL_AGAINST_BASE_DETAILS = "Select (SUM(AmountRequired)-IFNULL(SUM(ExcessReferenceAmount),0)) 'Amt',DATE_FORMAT(MAX(Col2),'%d %b, %Y') 'Dates' from bill_against_base where `Status`!='Bill Rejected' And ReferenceTransactionID=@TransId And ReferenceSequenceID=@SeqNo GROUP BY ReferenceTransactionID,ReferenceSequenceID;";
        public const string BILL_DISTRIBUTION_ADVANCE_DETAILS = "Select * from billdistribution_advance where Id=@TransId And SeqId=@SeqNo\r\n;";
        public const string YEAR_WISE_RECORD = "select '' as 'SNO',CAST(IFNULL(DATE_FORMAT(B.SignedOn,'%Y'),'Not Yet') as CHAR) 'Name',CAST(IFNULL(DATE_FORMAT(B.SignedOn,'%Y'),'Not Yet') as CHAR) 'MyYear',CAST(IFNULL(DATE_FORMAT(B.SignedOn,'%b, %Y'),'Not Yet') as CHAR) 'Month',SUM(B.IssuedAmount) 'Req',SUM(if(B.SignedOn is not null,B.IssuedAmount,0)) 'Signed',SUM(if(B.Col4 is not null,B.IssuedAmount,0)) 'Cleared' from bill_base A, bill_transaction_issue B where A.TransactionID=B.TransactionID And B.Col3 is  NULL @Condition GROUP BY YEAR(B.SignedOn),MONTH(B.SignedOn) ORDER BY YEAR(B.SignedOn) Desc,MONTH(B.SignedOn)  Desc";
        public const string PERSON_WISE_REPORT = "select '' as 'SNO',MAX(RelativePersonName) 'Name',CAST(IFNULL(DATE_FORMAT(B.SignedOn,'%Y'),'Not Yet') as CHAR) 'MyYear',CAST(IFNULL(DATE_FORMAT(B.SignedOn,'%b, %Y'),'Not Yet') as CHAR) 'Month',SUM(B.IssuedAmount) 'Req',SUM(if(B.SignedOn is not null,B.IssuedAmount,0)) 'Signed',SUM(if(B.Col4 is not null,B.IssuedAmount,0)) 'Cleared' from bill_base A, bill_transaction_issue B where A.TransactionID=B.TransactionID And B.Col3 is  NULL @Condition GROUP BY RelativePersonID,YEAR(B.SignedOn),MONTH(B.SignedOn) ORDER BY RelativePersonName,YEAR(B.SignedOn) Desc,MONTH(B.SignedOn)  Desc;";
        public const string HEAD_WISE_DETAILS = "select '' as 'SNO',UPPER(IF(B.CVAddName is NULL OR B.CVAddName='---','---',B.CVAddName)) 'Name',CAST(IFNULL(DATE_FORMAT(B.SignedOn,'%Y'),'Not Yet') as CHAR) 'MyYear',CAST(IFNULL(DATE_FORMAT(B.SignedOn,'%b, %Y'),'Not Yet') as CHAR) 'Month',SUM(B.IssuedAmount) 'Req',SUM(if(B.SignedOn is not null,B.IssuedAmount,0)) 'Signed',SUM(if(B.Col4 is not null,B.IssuedAmount,0)) 'Cleared' from bill_base A, bill_transaction_issue B where A.TransactionID=B.TransactionID And B.Col3 is  NULL @Condition GROUP BY IF(B.CVAddName is NULL OR B.CVAddName='---','---',B.CVAddName),YEAR(B.SignedOn),MONTH(B.SignedOn) ORDER BY IF(B.CVAddName is NULL OR B.CVAddName='---','---',B.CVAddName),YEAR(B.SignedOn) Desc,MONTH(B.SignedOn)  Desc";
    }
}
